language: node_js
node_js:
  - "stable"
cache: npm
script:
  - npm run build
  - npm run test:unit
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
